title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

docs:
- title: Principal
  url: index.html 

- title: Otra PÃ¡gina
  url: another-page.html 

